import matplotlib.pyplot as plt
import os

def generate_visuals_and_docs():
    # Target Companies from My Quotes (Derived from Nasdaq image data)
    targets = {
        'CVX': {'type': 'Common', 'yield': 'TBA', 'data_source': 'Nasdaq Visual (Null)'},
        'JEPQ': {'type': 'ETF (Covered Call)', 'yield': 'Monitor', 'data_source': 'NDX Yield Source'},
        'IBM': {'type': 'Common', 'yield': 'TBA', 'data_source': 'OTC/External'},
        'TSLA': {'type': 'Common (Non-Payer)', 'yield': '0.00%', 'data_source': 'Verified'},
        'JPM': {'type': 'Common', 'yield': 'TBA', 'data_source': 'OTC/External'},
        'NDX': {'type': 'Index (Underlying)', 'yield': 'N/A', 'data_source': 'N/A'}
    }

    # Generate Chart (Yield Monitor Status)
    plt.figure(figsize=(9, 4.5), facecolor='#0a0a0a')
    ax = plt.gca()
    ax.set_facecolor('#0a0a0a')
    
    # We graph a monitor bar chart based on data availability state
    status_states = [1, 0, 0, 1, 0] # 1=Verified, 0=TBA/Monitor (Null Source)
    tickers = ['TSLA', 'CVX', 'JEPQ', 'JPM', 'IBM']
    plt.bar(tickers, status_states, color=['#00ff00', '#222', '#222', '#222', '#222'])
    
    plt.title("Dividend Data Availability State (1=Verified, 0=Null/Monitor)", color='white')
    plt.ylabel("Data Integrity State", color='white')
    plt.tick_params(colors='white')
    plt.grid(axis='y', color='#333', linestyle='--')

    plt.savefig('div_status.png')
    print("[PYTHON 3.15] Dividend status asset generated: div_status.png")

    # Sync README structure
    sync_readme(targets)

def sync_readme(targets):
    base_readme = """# 🌌 Stargate v13.0: Event Horizon
### Geopolitical Inflection Suite | April 7, 2026
**Current Status:** [BEARISH CONTROL] 🔴

---

## 📊 Live Telemetry Dashboard
![Stargate Dashboard](stargate_dashboard.svg)

---

## 🛰️ Strategic Intelligence Report (17:35 BRT Update)
> **The Deadline:** Trump’s 8:00 PM EST ultimatum is the "hard pivot." Market is pricing in zero delay.

> **Dividend Anomaly (CVX):** Per verified Nasdaq data (Apr 7, 16:29 EST), Chevron Corporation Common Stock (CVX) has entered a **"Non-Nasdaq symbol" state** for Dividend History. This null state (per `image_1.png`) means automated yield monitoring for CVX is currently **disabled**.

> **Monitor Cluster:** Actively listening for 20:00 EST news. Next move belongs to Tehran.

---

## 📈 Yield Integrity Monitor (Cluster-Wide)
Generated by **Python 3.15**. Trackers targeting [TSLA, CVX, JEPQ, JPM, IBM].

![Dividend Status](div_status.png)

### Company-Specific Monitor Manifest:
"""
    manifest = "| Ticker | Asset Type | Reported Yield | Visual Data Source |\\n| :--- | :--- | :--- | :--- |\\n"
    for t, data in targets.items():
        # Exclude NDX as underlying index
        if t != 'NDX':
            yield_str = f"**{data['yield']}**" if data['yield'] != 'TBA' else "TBA (OTC)"
            manifest += f"| {t} | {data['type']} | {yield_str} | {data['data_source']} |\\n"
    
    readme_content = base_readme + manifest
    
    with open("README.md", "w") as f:
        f.write(readme_content)
    print("[PYTHON 3.15] README.md synchronized with yield intelligence manifest.")

if __name__ == "__main__":
    generate_visuals_and_docs()
